Select * FROM  constrains
-- INSERT INTO constrains(id , NAME , AGE , GENDER , PHONE , CITY)
-- VALUES(5 , " LOVE BROOK ", 20, "FEMALE" ,"482920138" , " ARTIC FOX" )
-- WHERE AGE >=18 AND AGE <20 ; AND CONDITION ON ONLY ONE ATTRIBUTE 
-- WHERE AGE <=20 AND GENDER ="MALE" -- AND CONDITION ON TWO DIFFERENT  ATTRIBUTES

-- WHERE AGE <20 OR  CITY=" ARTIC FOX"
-- WHERE (AGE <20 OR CITY= "ARTIC FOX") AND GENDER="MALE"
-- WHERE NOT CITY = "MUMBAI" OR CITY ="ARTIC FOX"

WHERE NOT AGE<20 